name: Deploy to Firebase Hosting (motm-neutral)

on:
  push:
    branches: [ main ]
    paths:
      - 'neutral/**'
      - 'firebase.json'
      - '.github/workflows/firebase-hosting-neutral.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional debug to make sure files are where we expect
      - name: Verify repo layout
        run: |
          echo "PWD = $(pwd)"
          ls -la
          test -f firebase.json || (echo "firebase.json not found at repo root" && exit 1)
          test -d neutral || (echo "neutral/ folder not found" && exit 1)
          test -f neutral/index.html || (echo "neutral/index.html missing" && exit 1)

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOTM_NEUTRAL }}'
          projectId: motm-neutral
          channelId: live
          entryPoint: ./     # <— folder containing firebase.json (repo root)
